version: "3"

services:
  poll:
    build: ./poll
    restart: always
    links:
      - redis
      - db
    depends_on:
      - redis
    ports:
      - "5000:80"
    networks:
      - poll-tier
    environment:
      - 0.0.0.0

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier

  worker:
    build: ./worker
    restart: always
    depends_on:
      - db
      - redis
    networks:
      - back-tier
    environment:
      - 0.0.0.0

  db:
    image: postgres:latest
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    networks:
      - result-tier
      - back-tier

  result:
    build: ./result
    restart: always
    depends_on:
      - db
    ports:
      - "5001:80"
    networks:
      - result-tier
    environment:
      - 0.0.0.0

networks:
  poll-tier:
      driver: bridge
  result-tier:
      driver: bridge
  back-tier:
      driver: bridge

volumes:
  db-data: